name: Python CI

on:
    push:
    branches:
      - main  # Rodar o CI ao fazer push na branch main
    pull_request:
    branches:
      - main  # Rodar o CI ao abrir um pull request na branch main

jobs:
  build:
    runs-on: ubuntu-latest  # A pipeline rodará em uma máquina virtual Ubuntu

    steps:
      - name: Check out the code
        uses: actions/checkout@v2  # Faz checkout do código do repositório

      - name: Set up Python
        uses: actions/setup-python@v2  # Configura o ambiente Python
        with:
          python-version: '3.x'  # Especifica a versão do Python (substitua '3.x' por uma versão específica, se preferir)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Atualiza o pip
          pip install -r requirements.txt  # Instala as dependências listadas no arquivo requirements.txt

      - name: Run tests
        run: |
          pytest  # Executa os testes definidos usando pytest
